// Bilingual UI strings (English + Kannada). The conversational backend also
// accepts Kannada keywords; this covers the static chrome.
export const STRINGS = {
  en: {
    appTitle: 'KSP Crime Intelligence Platform',
    subtitle: 'Karnataka State Police · Conversational Crime Analytics',
    tabs: { chat: 'Assistant', dashboard: 'Analytics', network: 'Networks' },
    chatPlaceholder: 'Ask about FIRs, hotspots, offenders, trends…',
    send: 'Ask',
    exportPdf: 'Export conversation (PDF)',
    evidence: 'Evidence trail',
    queryRun: 'ZCQL executed',
    rows: 'rows',
    kpiTotal: 'Total FIRs',
    kpiHeinous: 'Heinous',
    kpiArrests: 'Arrests / Surrenders',
    kpiChargesheet: 'Chargesheeted',
    trend: 'Monthly crime trend',
    byHead: 'By crime head',
    byStatus: 'By case status',
    byDistrict: 'District hotspots',
    demographics: 'Socio-demographic insights',
    ageBand: 'Complainant age bands',
    gender: 'By gender',
    occupation: 'By occupation',
    topOffenders: 'Top repeat offenders (risk-scored)',
    gangs: 'Detected groups',
    risk: 'Risk',
    cases: 'cases',
    coOffenders: 'co-offenders',
    focusHint: 'Click an offender to focus their network',
    clearFocus: 'Show full network',
    examples: 'Try:',
    exampleQs: [
      'How many theft cases in Mysuru in 2025?',
      'Where are the crime hotspots?',
      'Show me repeat offenders',
      'What is the case status breakdown?',
      'Monthly trend of cyber crimes',
    ],
  },
  kn: {
    appTitle: 'ಕೆಎಸ್‌ಪಿ ಅಪರಾಧ ಗುಪ್ತಚರ ವೇದಿಕೆ',
    subtitle: 'ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ · ಸಂಭಾಷಣಾ ಅಪರಾಧ ವಿಶ್ಲೇಷಣೆ',
    tabs: { chat: 'ಸಹಾಯಕ', dashboard: 'ವಿಶ್ಲೇಷಣೆ', network: 'ಜಾಲಗಳು' },
    chatPlaceholder: 'ಎಫ್‌ಐಆರ್, ಹಾಟ್‌ಸ್ಪಾಟ್, ಅಪರಾಧಿಗಳ ಬಗ್ಗೆ ಕೇಳಿ…',
    send: 'ಕೇಳಿ',
    exportPdf: 'ಸಂಭಾಷಣೆ ರಫ್ತು (PDF)',
    evidence: 'ಸಾಕ್ಷ್ಯ ಜಾಡು',
    queryRun: 'ZCQL ಚಲಾಯಿಸಲಾಗಿದೆ',
    rows: 'ಸಾಲುಗಳು',
    kpiTotal: 'ಒಟ್ಟು ಎಫ್‌ಐಆರ್',
    kpiHeinous: 'ಘೋರ',
    kpiArrests: 'ಬಂಧನಗಳು',
    kpiChargesheet: 'ಆರೋಪಪಟ್ಟಿ',
    trend: 'ಮಾಸಿಕ ಅಪರಾಧ ಪ್ರವೃತ್ತಿ',
    byHead: 'ಅಪರಾಧ ವಿಧದ ಪ್ರಕಾರ',
    byStatus: 'ಪ್ರಕರಣ ಸ್ಥಿತಿಯ ಪ್ರಕಾರ',
    byDistrict: 'ಜಿಲ್ಲಾ ಹಾಟ್‌ಸ್ಪಾಟ್',
    demographics: 'ಸಾಮಾಜಿಕ-ಜನಸಂಖ್ಯಾ ಒಳನೋಟಗಳು',
    ageBand: 'ದೂರುದಾರರ ವಯಸ್ಸು',
    gender: 'ಲಿಂಗದ ಪ್ರಕಾರ',
    occupation: 'ವೃತ್ತಿಯ ಪ್ರಕಾರ',
    topOffenders: 'ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿಗಳು (ಅಪಾಯ ಸ್ಕೋರ್)',
    gangs: 'ಪತ್ತೆಯಾದ ಗುಂಪುಗಳು',
    risk: 'ಅಪಾಯ',
    cases: 'ಪ್ರಕರಣಗಳು',
    coOffenders: 'ಸಹ-ಅಪರಾಧಿಗಳು',
    focusHint: 'ಜಾಲ ಕೇಂದ್ರೀಕರಿಸಲು ಅಪರಾಧಿಯನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ',
    clearFocus: 'ಪೂರ್ಣ ಜಾಲ ತೋರಿಸಿ',
    examples: 'ಪ್ರಯತ್ನಿಸಿ:',
    exampleQs: [
      'ಮೈಸೂರಿನಲ್ಲಿ 2025 ರಲ್ಲಿ ಎಷ್ಟು ಕಳ್ಳತನ ಪ್ರಕರಣಗಳು?',
      'ಅಪರಾಧ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಎಲ್ಲಿವೆ?',
      'ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿಗಳನ್ನು ತೋರಿಸಿ',
      'ಪ್ರಕರಣ ಸ್ಥಿತಿಯ ವಿಭಜನೆ ಏನು?',
      'ಸೈಬರ್ ಅಪರಾಧಗಳ ಮಾಸಿಕ ಪ್ರವೃತ್ತಿ',
    ],
  },
};
